sudo: required
language: python
dist: precise
matrix:
  include:
    # https://docs.python.org/devguide/#status-of-python-branches
    # One build pulls latest versions dynamically
    - python: 3.6
      env: CDH=cdh5 CDH_VERSION=5 PRESTO=RELEASE SQLALCHEMY=sqlalchemy
    # Others use pinned versions.
    - python: 3.5
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==1.0.12
    - python: 3.4
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==1.0.12
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==1.0.12
    # stale stuff we're still using / supporting
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==0.7.10
  # exclude: python 3 against old libries
install:
  - ./scripts/travis-install.sh
  - pip install codecov
# sleep so Presto has time to start up. Otherwise we might get 'No nodes available to run query'
script: sleep 10 && PYTHONHASHSEED=random pytest -v
after_success: codecov
